apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: delivery-pizza
  # You'll usually want to add your resources to the argocd namespace.
  namespace: default
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: https://github.com/MahmoudG27/CD-APP.git
    targetRevision: master
    path: manifest/
  destination:
    server: https://kubernetes.default.svc
    namespace: delivery-pizza

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
