apiVersion: apps/v1
kind: Deployment
metadata:
  name: bake
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: sample 
  template:
  # pod definition
    metadata:
      name: sample
      labels:
        app: sample
    spec:
      imagePullSecrets:
      - name: nexus-registry
      containers:
      - name: app
        #        image: elnabatshy/bake:v3
        image: http://98.71.95.8:8081/repository/bake-house/bake:v3
        ports:
        - containerPort: 80
