apiVersion: apps/v1
kind: Deployment
metadata:
  name: bake
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: sample 
  template:
  # pod definition
    metadata:
      name: sample
      labels:
        app: sample
    spec:
      containers:
      - name: app
        image: elnabatshy/bake:123
        ports:
        - containerPort: 80
